### ISSUE TITLE
Builder.io not working

### ISSUE THREAD

**Issue by playbookTV** [BuilderIO/html-figma#31]
I just tried to use the plugin on figma and i got the error "TypeError: Failed to fetch"
Also, the main website is down.

Is there a problem?

**Comment by M4N0JKUM4R** [comment]
Did you solve it?

**Comment by steve8708** [comment]
hey all - should be solved, I'm guessing this happened once a while back during a brief outage period. But if you or anyone runs into this again just let us know, and thanks for reporting!

**Comment by Plutobby** [comment]
I just tried to use the plugin on figma and i got the error "TypeError: Failed to fetch"
Also, the main website is down.

Is there a problem?

**Comment by steve8708** [comment]
hey @Plutobby - we will take a look into your error on our backend. What website is down though? https://www.builder.io is up for me, is not for you?

**Comment by Plutobby** [comment]
It was prolly my network.. still have issues with the figma plugin tho
